<?php

return [
    'type' => 'variable',
    'variants' => [
        'tiles.1' => [
            'name' => 'Плитки 1',
            'properties' => [
                'margin' => [
                    'bottom' => ['value' => 50, 'measure' => 'px']
                ]
            ],
            'component' => [
                'code' => 'intec.universe:main.shares',
                'template' => 'template.1',
                'properties' => [
                    'IBLOCK_TYPE' => '#CONTENT_SHARES_IBLOCK_TYPE#',
                    'IBLOCK_ID' => '#CONTENT_SHARES_IBLOCK_ID#',
                    'ELEMENTS_COUNT' => '3',
                    'SETTINGS_USE' => 'Y',
                    'LAZYLOAD_USE' => 'N',
                    'ELEMENT_HEADER_PROPERTY_TEXT' => 'DURATION',
                    'TIMER_PROPERTY_UNTIL_DATE' => 'ACTION_END',
                    'HEADER_BLOCK_SHOW' => 'Y',
                    'HEADER_BLOCK_POSITION' => 'center',
                    'HEADER_BLOCK_TEXT' => 'Акции',
                    'DESCRIPTION_BLOCK_SHOW' => 'N',
                    'LINE_COUNT' => 3,
                    'LINK_USE' => 'Y',
                    'LINK_ALL_SHOW' => 'Y',
                    'LINK_ALL_PLACE' => 'bottom',
                    'LINK_ALL_POSITION' => 'right',
                    'LINK_ALL_TEXT' => 'Все акции',
                    'ELEMENT_HEADER_SHOW' => 'Y',
                    'TIMER_SHOW' => 'Y',
                    'TIMER_USE' => 'Y',
                    'TIMER_TIMER_SECONDS_SHOW' => 'N',
                    'TIMER_TIMER_HEADER_SHOW' => 'Y',
                    'TIMER_TIMER_HEADER' => 'До конца акции',
                    'TIMER_SALE_SHOW' => 'Y',
                    'TIMER_PROPERTY_DISCOUNT' => 'SALE',
                    'TIMER_SALE_HEADER_SHOW' => 'N',
                    'LIST_PAGE_URL' => '',
                    'SECTION_URL' => '',
                    'DETAIL_URL' => '',
                    'NAVIGATION_USE' => 'Y',
                    'NAVIGATION_ID' => 'news',
                    'NAVIGATION_MODE' => 'ajax',
                    'NAVIGATION_TEMPLATE' => 'lazy.2',
                    'SORT_BY' => 'SORT',
                    'ORDER_BY' => 'ASC',
                    'DATE_SHOW' => 'Y',
                    'DATE_FORMAT' => 'd.m.Y',
                    'SEE_ALL_SHOW' => 'N',
                    'SECTION_URL' => '',
                    'DETAIL_URL' => '',
                    'CACHE_TYPE' => 'A',
                    'CACHE_TIME' => 3600000,
                    'SORT_BY' => 'SORT',
                    'ORDER_BY' => 'ASC'
                ]
            ]
        ],
        'blocks.1' => [
            'name' => 'Блоки 1',
            'properties' => [
                'margin' => [
                    'bottom' => ['value' => 50, 'measure' => 'px']
                ]
            ],
            'component' => [
                'code' => 'intec.universe:main.shares',
                'template' => 'template.2',
                'properties' => [
                    'IBLOCK_TYPE' => '#CONTENT_SHARES_IBLOCK_TYPE#',
                    'IBLOCK_ID' => '#CONTENT_SHARES_IBLOCK_ID#',
                    'ELEMENTS_COUNT' => '2',
                    'SETTINGS_USE' => 'Y',
                    'LAZYLOAD_USE' => 'N',
                    'TIMER_USE' => 'Y',
                    'ELEMENT_HEADER_PROPERTY_TEXT' => 'DURATION',
                    'TIMER_PROPERTY_UNTIL_DATE' => 'ACTION_END',
                    'HEADER_BLOCK_SHOW' => 'Y',
                    'HEADER_BLOCK_POSITION' => 'center',
                    'HEADER_BLOCK_TEXT' => 'Акции',
                    'DESCRIPTION_BLOCK_SHOW' => 'N',
                    'LINE_COUNT' => 1,
                    'LINK_USE' => 'Y',
                    'DESCRIPTION_USE' => 'Y',
                    'ELEMENT_HEADER_SHOW' => 'Y',
                    'LINK_ALL_SHOW' => 'Y',
                    'PREVIEW_SHOW' => 'Y',
                    'PREVIEW_TRUNCATE_USE' => 'Y',
                    'PREVIEW_TRUNCATE_WORDS' => 30,
                    'TIMER_SHOW' => 'Y',
                    'TIMER_TIMER_SECONDS_SHOW' => 'N',
                    'TIMER_TIMER_HEADER_SHOW' => 'Y',
                    'TIMER_TIMER_HEADER' => 'До конца акции',
                    'TIMER_SALE_SHOW' => 'Y',
                    'TIMER_PROPERTY_DISCOUNT' => 'SALE',
                    'TIMER_SALE_HEADER_SHOW' => 'N',
                    'LIST_PAGE_URL' => '',
                    'SECTION_URL' => '',
                    'DETAIL_URL' => '',
                    'NAVIGATION_USE' => 'Y',
                    'NAVIGATION_ID' => 'news',
                    'NAVIGATION_MODE' => 'ajax',
                    'NAVIGATION_TEMPLATE' => 'lazy.2',
                    'SORT_BY' => 'SORT',
                    'ORDER_BY' => 'ASC',
                    'DATE_SHOW' => 'Y',
                    'DATE_FORMAT' => 'd.m.Y',
                    'SEE_ALL_SHOW' => 'Y',
                    'SEE_ALL_PLACE' => 'top',
                    'SEE_ALL_POSITION' => 'right',
                    'SEE_ALL_TEXT' => 'Все акции',
                    'NAVIGATION_ALL' => 'N',
                    'PAGINATION_USE' => 'Y',
                    'PAGINATION_AJAX' => 'Y',
                    'PAGINATION_TEMPLATE' => 'lazy.1',
                    'PAGINATION_NAME' => 'Акции',
                    'PAGINATION_REVERSE' => 'Y',
                    'PAGINATION_ALWAYS' => 'Y',
                    'PAGINATION_ALL' => 'Y',
                    'PAGINATION_WINDOW' => '5',
                    'PAGINATION_SAVE' => 'N',
                    'CACHE_TYPE' => 'A',
                    'CACHE_TIME' => 3600000,
                    'SORT_BY' => 'SORT',
                    'ORDER_BY' => 'ASC'
                ]
            ]
        ],
        'blocks.2' => [
            'name' => 'Блоки 2',
            'properties' => [
                'margin' => [
                    'top' => ['value' => 50, 'measure' => 'px'],
                    'bottom' => ['value' => 50, 'measure' => 'px']
                ]
            ],
            'component' => [
                'code' => 'intec.universe:main.shares',
                'template' => 'template.6',
                'properties' => [
                    'IBLOCK_TYPE' => '#CONTENT_SHARES_IBLOCK_TYPE#',
                    'IBLOCK_ID' => '#CONTENT_SHARES_IBLOCK_ID#',
                    'SECTIONS' => [],
                    'ELEMENTS_COUNT' => '2',
                    'SETTINGS_USE' => 'Y',
                    'LAZYLOAD_USE' => 'N',
                    'TIMER_USE' => 'Y',
                    'ELEMENT_HEADER_PROPERTY_TEXT' => 'DURATION',
                    'TIMER_PROPERTY_UNTIL_DATE' => 'ACTION_END',
                    'HEADER_BLOCK_SHOW' => 'Y',
                    'HEADER_BLOCK_POSITION' => 'center',
                    'HEADER_BLOCK_TEXT' => 'Акции',
                    'DESCRIPTION_BLOCK_SHOW' => 'N',
                    'LINE_COUNT' => '2',
                    'LINK_USE' => 'Y',
                    'PICTURE_SHOW' => 'Y',
                    'DESCRIPTION_USE' => 'Y',
                    'ELEMENT_HEADER_SHOW' => 'Y',
                    'LINK_ALL_SHOW' => 'Y',
                    'PREVIEW_SHOW' => 'Y',
                    'PREVIEW_TRUNCATE_USE' => 'Y',
                    'PREVIEW_TRUNCATE_WORDS' => 30,
                    'TIMER_SHOW' => 'Y',
                    'TIMER_TIMER_SECONDS_SHOW' => 'N',
                    'TIMER_TIMER_HEADER_SHOW' => 'Y',
                    'TIMER_TIMER_HEADER' => 'До конца акции',
                    'TIMER_SALE_SHOW' => 'Y',
                    'TIMER_PROPERTY_DISCOUNT' => 'SALE',
                    'TIMER_SALE_HEADER_SHOW' => 'N',
                    'LIST_PAGE_URL' => '',
                    'SECTION_URL' => '',
                    'DETAIL_URL' => '',
                    'NAVIGATION_USE' => 'Y',
                    'NAVIGATION_ID' => 'news',
                    'NAVIGATION_MODE' => 'ajax',
                    'NAVIGATION_TEMPLATE' => 'lazy.2',
                    'SORT_BY' => 'SORT',
                    'ORDER_BY' => 'ASC',
                    'DATE_SHOW' => 'Y',
                    'DATE_FORMAT' => 'd.m.Y',
                    'SEE_ALL_SHOW' => 'Y',
                    'SEE_ALL_PLACE' => 'top',
                    'SEE_ALL_POSITION' => 'right',
                    'SEE_ALL_TEXT' => 'Все акции',
                    'NAVIGATION_ALL' => 'N',
                    'PAGINATION_USE' => 'Y',
                    'PAGINATION_AJAX' => 'Y',
                    'PAGINATION_TEMPLATE' => 'lazy.1',
                    'PAGINATION_NAME' => 'Акции',
                    'PAGINATION_REVERSE' => 'Y',
                    'PAGINATION_ALWAYS' => 'Y',
                    'PAGINATION_ALL' => 'Y',
                    'PAGINATION_WINDOW' => '5',
                    'PAGINATION_SAVE' => 'N',
                    'CACHE_TYPE' => 'A',
                    'CACHE_TIME' => 3600000,
                    'SORT_BY' => 'SORT',
                    'ORDER_BY' => 'ASC'
                ]
            ]
        ],
        'tiles.2' => [
            'name' => 'Плитки 2',
            'properties' => [
                'margin' => [
                    'bottom' => ['value' => 50, 'measure' => 'px']
                ]
            ],
            'component' => [
                'code' => 'intec.universe:main.shares',
                'template' => 'template.3',
                'properties' => [
                    'IBLOCK_TYPE' => '#CONTENT_SHARES_IBLOCK_TYPE#',
                    'IBLOCK_ID' => '#CONTENT_SHARES_IBLOCK_ID#',
                    'ELEMENTS_COUNT' => '4',
                    'SETTINGS_USE' => 'Y',
                    'LAZYLOAD_USE' => 'N',
                    'TIMER_USE' => 'Y',
                    'TIMER_SHOW' => 'Y',
                    'ELEMENT_HEADER_PROPERTY_TEXT' => 'DURATION',
                    'TIMER_PROPERTY_UNTIL_DATE' => 'ACTION_END',
                    'HEADER_BLOCK_SHOW' => 'Y',
                    'HEADER_BLOCK_POSITION' => 'center',
                    'HEADER_BLOCK_TEXT' => 'Акции',
                    'DESCRIPTION_BLOCK_SHOW' => 'N',
                    'LINE_COUNT' => 2,
                    'LINK_USE' => 'Y',
                    'LINK_ALL_SHOW' => 'Y',
                    'LINK_ALL_POSITION' => 'right',
                    'LINK_ALL_TEXT' => 'Показать все',
                    'ELEMENT_HEADER_SHOW' => 'Y',
                    'TIMER_TIMER_SECONDS_SHOW' => 'N',
                    'TIMER_SALE_SHOW' => 'Y',
                    'TIMER_PROPERTY_DISCOUNT' => 'SALE',
                    'LIST_PAGE_URL' => '',
                    'SECTION_URL' => '',
                    'DETAIL_URL' => '',
                    'NAVIGATION_USE' => 'Y',
                    'NAVIGATION_ID' => 'news',
                    'NAVIGATION_MODE' => 'ajax',
                    'NAVIGATION_TEMPLATE' => 'lazy.2',
                    'SORT_BY' => 'SORT',
                    'ORDER_BY' => 'ASC',
                    'DESCRIPTION_USE' => 'Y',
                    'SEE_ALL_SHOW' => 'N',
                    'NAVIGATION_ALL' => 'N',
                    'CACHE_TYPE' => 'A',
                    'CACHE_TIME' => 3600000,
                    'SORT_BY' => 'SORT',
                    'ORDER_BY' => 'ASC'
                ]
            ]
        ]
    ]
];
