<?php

use Bitrix\Main\Localization\Loc;

return [
    [
        'name' => Loc::getMessage('PRESETS_HEADER_TEMPLATE_1_PRESET_DEFAULT_1'),
        'group' => 'header',
        'properties' => [
            'SETTINGS_USE' => 'Y',
            'SEARCH_NUM_CATEGORIES' => 1,
            'SEARCH_TOP_COUNT' => 5,
            'SEARCH_ORDER' => 'date',
            'SEARCH_USE_LANGUAGE_GUESS' => 'Y',
            'SEARCH_CHECK_DATES' => 'N',
            'SEARCH_SHOW_OTHERS' => 'N',
            'SEARCH_TIPS_USE' => 'Y',
            'COMPARE_CODE' => 'compare',
            'MENU_MAIN_ROOT' => 'top',
            'MENU_MAIN_CHILD' => 'left',
            'MENU_MAIN_LEVEL' => 4,
            'MENU_INFO_ROOT' => 'footer',
            'MENU_INFO_CHILD' => 'left',
            'MENU_INFO_LEVEL' => 1,
            'BANNER_BLOCKS_COUNT' => 2,
            'BANNER_ELEMENTS_COUNT' => '',
            'LOGOTYPE' => '/include/logotype.php',
            'PHONES' => [
                '+7 (000) 000 00 00'
            ],
            'ADDRESS' => Loc::getMessage('PRESETS_HEADER_TEMPLATE_1_ADDRESS'),
            'EMAIL' => Loc::getMessage('PRESETS_HEADER_TEMPLATE_1_EMAIL'),
            'TAGLINE' => Loc::getMessage('PRESETS_HEADER_TEMPLATE_1_TAGLINE'),
            'MENU_MAIN_PROPERTY_IMAGE' => 'UF_IMAGE_MENU',
            'FORMS_CALL_ID' => 1,
            'FORMS_CALL_TEMPLATE' => '.default',
            'SOCIAL_VK' => 'https://vk.com',
            'SOCIAL_INSTAGRAM' => 'https://instagram.com',
            'SOCIAL_FACEBOOK' => 'https://facebook.com',
            'SOCIAL_TWITTER' => 'https://twitter.com',
            'SOCIAL_YOUTUBE' => 'https://youtube.com',
            'SOCIAL_ODNOKLASSNIKI' => 'https://ok.ru',
            'BANNER_PROPERTY_HEADER' => 'HEADER',
            'BANNER_PROPERTY_DESCRIPTION' => 'DESCRIPTION',
            'BANNER_PROPERTY_HEADER_COLOR' => 'TITLE_TEXT_COLOR',
            'BANNER_PROPERTY_DESCRIPTION_COLOR' => 'DESCRIPTION_TEXT_COLOR',
            'BANNER_PROPERTY_TEXT_POSITION' => 'POSITION',
            'BANNER_PROPERTY_LINK' => 'LINK',
            'BANNER_PROPERTY_LINK_BLANK' => 'NEW_TAB',
            'BANNER_PROPERTY_BUTTON_SHOW' => 'BUTTON_SHOW',
            'BANNER_PROPERTY_BUTTON_TEXT' => 'BUTTON_TEXT',
            'BANNER_PROPERTY_BUTTON_TEXT_COLOR' => 'BUTTON_TEXT_COLOR',
            'BANNER_PROPERTY_BUTTON_COLOR' => 'BUTTON_COLOR',
            'BANNER_PROPERTY_BANNER_COLOR' => 'BANNER_COLOR',
            'BANNER_PROPERTY_INSERTIONS' => 'INSERTIONS',
            'BANNER_PROPERTY_VIDEO_URL' => 'VIDEO_LINK',
            'BANNER_BLOCKS_PROPERTY_LINK' => 'LINK',
            'BANNER_BLOCKS_PROPERTY_LINK_BLANK' => 'LINK_BLANK',
            'LOGOTYPE_SHOW' => 'Y',
            'PHONES_SHOW' => 'Y',
            'TRANSPARENCY' => 'Y',
            'LOGOTYPE_SHOW_FIXED' => 'Y',
            'LOGOTYPE_SHOW_MOBILE' => 'Y',
            'ADDRESS_SHOW' => 'Y',
            'EMAIL_SHOW' => 'Y',
            'AUTHORIZATION_SHOW' => 'Y',
            'AUTHORIZATION_SHOW_FIXED' => 'Y',
            'AUTHORIZATION_SHOW_MOBILE' => 'Y',
            'TAGLINE_SHOW' => 'Y',
            'SEARCH_SHOW' => 'Y',
            'SEARCH_SHOW_FIXED' => 'Y',
            'SEARCH_SHOW_MOBILE' => 'Y',
            'BASKET_SHOW' => 'Y',
            'BASKET_SHOW_FIXED' => 'Y',
            'BASKET_SHOW_MOBILE' => 'Y',
            'DELAY_SHOW' => 'Y',
            'DELAY_SHOW_FIXED' => 'Y',
            'DELAY_SHOW_MOBILE' => 'Y',
            'COMPARE_SHOW' => 'Y',
            'COMPARE_SHOW_FIXED' => 'Y',
            'COMPARE_SHOW_MOBILE' => 'Y',
            'MENU_MAIN_SHOW' => 'Y',
            'MENU_MAIN_SHOW_FIXED' => 'Y',
            'MENU_MAIN_SHOW_MOBILE' => 'Y',
            'MENU_MAIN_DELIMITERS' => 'Y',
            'MENU_MAIN_SECTION_VIEW' => 'images',
            'MENU_MAIN_SECTION_ITEMS_COUNT' => 3,
            'MENU_MAIN_CATALOG_LINKS' => [
                '/catalog/'
            ],
            'FORMS_CALL_SHOW' => 'Y',
            'FORMS_CALL_TITLE' => Loc::getMessage('PRESETS_HEADER_TEMPLATE_1_FORMS_CALL_TITLE'),
            'DESKTOP' => 'template.1',
            'PHONES_POSITION' => 'bottom',
            'MENU_MAIN_POSITION' => 'bottom',
            'MENU_MAIN_TRANSPARENT' => 'N',
            'MENU_INFO_SHOW' => 'Y',
            'SOCIAL_SHOW' => 'Y',
            'SOCIAL_POSITION' => 'left',
            'MOBILE' => 'template.1',
            'MOBILE_FIXED' => 'N',
            'MOBILE_FILLED' => 'N',
            'FIXED' => 'template.1',
            'BANNER' => 'template.4',
            'BANNER_HEADER_SHOW' => 'Y',
            'BANNER_DESCRIPTION_SHOW' => 'Y',
            'BANNER_HEIGHT' => 600,
            'BANNER_INSERTIONS_SHOW' => 'Y',
            'BANNER_INSERTIONS_COUNT' => 3,
            'BANNER_SLIDER_DOTS' => 'Y',
            'BANNER_SLIDER_LOOP' => 'N',
            'BANNER_SLIDER_SPEED' => 500,
            'BANNER_SLIDER_AUTO_USE' => 'N',
            'CATALOG_URL' => '/catalog/',
            'LOGIN_URL' => '/personal/profile/',
            'PROFILE_URL' => '/personal/profile/',
            'PASSWORD_URL' => '/personal/profile/?forgot_password=yes',
            'REGISTER_URL' => '/personal/profile/?register=yes',
            'SEARCH_URL' => '/search/',
            'BASKET_URL' => '/personal/basket/',
            'COMPARE_URL' => '/catalog/compare.php',
            'CONSENT_URL' => '/company/consent/',
            'COMPOSITE_FRAME_MODE' => 'A',
            'COMPOSITE_FRAME_TYPE' => 'AUTO',
            'SEARCH_CATEGORY_0' => [
                'no'
            ],
            'SEARCH_PRICE_CODE' => [
                'BASE'
            ],
            'SEARCH_PRICE_VAT_INCLUDE' => 'Y',
            'SEARCH_CURRENCY_CONVERT' => 'Y',
            'SEARCH_CURRENCY_ID' => 'RUB',
            'BANNER_SORT_BY' => 'SORT',
            'BANNER_ORDER_BY' => 'ASC'
        ]
    ]
];