<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");

$APPLICATION->SetTitle("Отзывы");

?>
<?php $APPLICATION->IncludeComponent(
    "bitrix:news",
    "reviews.1",
    array(
        "COMPONENT_TEMPLATE" => "reviews.1",
        "IBLOCK_TYPE" => "content",
        "IBLOCK_ID" => "72",
        "NEWS_COUNT" => "20",
        "USE_SEARCH" => "N",
        "VIDEO_IBLOCK_TYPE" => "content",
        "VIDEO_IBLOCK_ID" => "81",
        "STAFF_IBLOCK_TYPE" => "content",
        "STAFF_IBLOCK_ID" => "74",
        "SETTINGS_USE" => "Y",
        "USE_RSS" => "N",
        "USE_RATING" => "N",
        "USE_CATEGORIES" => "N",
        "USE_REVIEW" => "Y",
        "USE_FILTER" => "N",
        "SORT_BY1" => "ACTIVE_FROM",
        "SORT_ORDER1" => "DESC",
        "SORT_BY2" => "SORT",
        "SORT_ORDER2" => "ASC",
        "CHECK_DATES" => "Y",
        "PROPERTY_INFORMATION" => "INFORMATION",
        "PROPERTY_RATING" => "RATING",
        "PROPERTY_PICTURES" => "PICTURES",
        "PROPERTY_FILES" => "FILES",
        "SEF_MODE" => "N",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "CACHE_TYPE" => "N",
        "CACHE_TIME" => "36000000",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "SET_LAST_MODIFIED" => "N",
        "SET_TITLE" => "Y",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
        "ADD_SECTIONS_CHAIN" => "Y",
        "ADD_ELEMENT_CHAIN" => "N",
        "USE_PERMISSIONS" => "N",
        "STRICT_SECTION_CHECK" => "N",
        "PREVIEW_TRUNCATE_LEN" => "",
        "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "LIST_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "LIST_PROPERTY_CODE" => array(
            0 => "VIDEO",
            1 => "INFORMATION",
            2 => "RESPONSE",
            3 => "VIDEO_MODE",
            4 => "RATING",
            5 => "STAFF",
            6 => "",
        ),
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "LIST_TEMPLATE" => "list.1",
        "DISPLAY_NAME" => "Y",
        "META_KEYWORDS" => "-",
        "META_DESCRIPTION" => "-",
        "BROWSER_TITLE" => "-",
        "DETAIL_SET_CANONICAL_URL" => "N",
        "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "DETAIL_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "DETAIL_PROPERTY_CODE" => array(
            0 => "",
            1 => "",
        ),
        "DETAIL_DISPLAY_TOP_PAGER" => "N",
        "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
        "DETAIL_PAGER_TITLE" => "Страница",
        "DETAIL_PAGER_TEMPLATE" => "",
        "DETAIL_PAGER_SHOW_ALL" => "Y",
        "PAGER_TEMPLATE" => ".default",
        "DISPLAY_TOP_PAGER" => "N",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "PAGER_TITLE" => "Новости",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "SET_STATUS_404" => "N",
        "SHOW_404" => "N",
        "MESSAGE_404" => "",
        "LIST_PROPERTY_TEXT" => "",
        "LIST_PROPERTY_ANSWER" => "RESPONSE",
        "LIST_PICTURE_SHOW" => "Y",
        "LIST_DATE_SHOW" => "Y",
        "SEND_USE" => "Y",
        "SEND_TEMPLATE" => "template.2",
        "SEND_CAPTCHA_USE" => "N",
        "SEND_FORM_ACCESS" => "all",
        "SEND_PROPERTY_FORM_FIELDS" => array(
            0 => "RATING",
            1 => "PREVIEW_TEXT",
            2 => "",
        ),
        "SEND_PROPERTY_FORM_REQUIRED" => array(
            0 => "",
            1 => "",
        ),
        "SEND_FORM_ADD_MODE" => "disabled",
        "SEND_PROPERTY_RATING" => "RATING",
        "SEND_FORM_SUBMIT_TEXT" => "Отправить отзыв",
        "SEND_CONSENT_URL" => "/company/consent/",
        "MESSAGES_PER_PAGE" => "10",
        "USE_CAPTCHA" => "Y",
        "REVIEW_AJAX_POST" => "Y",
        "PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
        "FORUM_ID" => "",
        "URL_TEMPLATES_READ" => "",
        "SHOW_LINK_TO_FORUM" => "Y",
        "PROPERTY_VIDEO" => "VIDEO",
        "PROPERTY_STAFF" => "STAFF",
        "SEND_FORM_ACCESS_AUTHORIZATION" => "/personal/profile/",
        "VIDEO_PROPERTY_URL" => "LINK",
        "STAFF_PROPERTY_POSITION" => "POSITION",
        "LIST_PROPERTY_VIDEO_VIEW" => "VIDEO_MODE",
        "LIST_INFORMATION_SHOW" => "Y",
        "LIST_RATING_SHOW" => "Y",
        "LIST_VIDEO_SHOW" => "N",
        "LIST_PICTURES_SHOW" => "Y",
        "LIST_FILES_SHOW" => "Y",
        "LIST_DATE_SOURCE" => "DATE_ACTIVE_FROM",
        "LIST_VIDEO_PICTURE_SOURCES" => array(
            0 => "service",
            1 => "",
        ),
        "LIST_VIDEO_PICTURE_QUALITY" => "hqdefault",
        "LIST_ANSWER_SHOW" => "Y",
        "LIST_ANSWER_DEFAULT_NAME" => "Администратор",
        "LIST_ANSWER_PICTURE_SHOW" => "Y",
        "LIST_ANSWER_POSITION_SHOW" => "Y",
        "SEND_RATING_USE" => "Y",
        "LIST_ANSWER_DEFAULT_PICTURE" => "",
        "LIST_ANSWER_DEFAULT_POSITION" => "Администратор",
        "VARIABLE_ALIASES" => array(
            "SECTION_ID" => "SECTION_ID",
            "ELEMENT_ID" => "ELEMENT_ID",
        )
    ),
    false
); ?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>