<?
$aMenuLinks = Array(
	Array(
		"Покупки", 
		"/help/buys/",
		Array(), 
		Array(), 
		"" 
	),
    Array(
        "Помощь покупателю",
        "/help/client/",
        Array(),
        Array(),
        ""
    ),
	Array(
		"Вопрос - ответ",
		"/help/faq/",
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Бренды", 
		"/help/brands/",
		Array(), 
		Array(), 
		"" 
	),
    Array(
        "Коллекции",
        "/collections/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Готовые образы",
        "/imagery/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Возможности",
        "/help/features/",
        Array(),
        Array(),
        ""
    )
);
?>