<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php"); ?>
<?php

$APPLICATION->SetTitle("Помощь покупателю");

?>
<?php $APPLICATION->IncludeComponent(
	"bitrix:news", 
	"help.1", 
	array(
		"IBLOCK_TYPE" => "content",
		"IBLOCK_ID" => "76",
		"NEWS_COUNT" => "20",
		"USE_SEARCH" => "N",
		"SETTINGS_USE" => "Y",
		"LAZYLOAD_USE" => "Y",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/help/client/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"USE_PERMISSIONS" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
		),
		"LIST_PROPERTY_CODE" => array(
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"LIST_TEMPLATE" => "1",
		"LIST_LAZYLOAD_USE" => "Y",
		"LIST_IBLOCK_DESCRIPTION_SHOW" => "Y",
		"LIST_BANNER_SHOW" => "Y",
		"LIST_BANNER_THEME" => "dark",
		"LIST_BANNER_TITLE_SHOW" => "Y",
		"LIST_BANNER_TITLE" => "Поможем разобраться!",
		"LIST_BANNER_SUBTITLE_SHOW" => "Y",
		"LIST_BANNER_SUBTITLE" => "Ответы нас интересующие вас вопросы в списке ниже",
		"LIST_ELEMENT_LINK_USE" => "N",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
		),
		"DETAIL_PROPERTY_CODE" => array(
		),
		"DETAIL_MENU_SHOW" => "N",
		"DETAIL_TEMPLATE" => "default.1",
		"DETAIL_LAZYLOAD_USE" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"FILE_404" => "/404.php",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_ID#/",
		)
	),
	false
);?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php"); ?>