<?php
class TopClientMod extends TopClient
{

	public function execute($request, $session = null, $bestUrl = null) {
		$resp = parent::execute($request, $session, $bestUrl); // TODO: Change the autogenerated stub
		usleep(500000);
		return $resp;
	}

}
