<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php") ?>
<?php

use Bitrix\Main\ModuleManager;

$APPLICATION->SetTitle("Корзина")

?>
<?php if (ModuleManager::isModuleInstalled('sale')) { ?>
    <? $APPLICATION->IncludeComponent(
        "bitrix:sale.basket.basket",
        "template.1",
        array(
            "DEFERRED_REFRESH" => "N",
            "USE_DYNAMIC_SCROLL" => "Y",
            "SHOW_FILTER" => "Y",
            "SHOW_RESTORE" => "Y",
            "ORDER_FAST_USE" => "Y",
            "ORDER_FAST_TEMPLATE" => ".default",
            "ORDER_FAST_AJAX_MODE" => "Y",
            "COLUMNS_LIST_EXT" => array(
                "PREVIEW_PICTURE",
                "DISCOUNT",
                "PROPS",
                "DELETE",
                "DELAY",
                "SUM"
            ),
            "COLUMNS_LIST_MOBILE" => array(
                "PREVIEW_PICTURE",
                "DISCOUNT",
                "DELETE",
                "DELAY",
                "SUM"
            ),
            "TOTAL_BLOCK_DISPLAY" => array(
                "top"
            ),
            "PRICE_DISPLAY_MODE" => "Y",
            "SHOW_DISCOUNT_PERCENT" => "Y",
            "DISCOUNT_PERCENT_POSITION" => "bottom-right",
            "PRODUCT_BLOCKS_ORDER" => "props,sku,columns",
            "USE_PRICE_ANIMATION" => "Y",
            "LABEL_PROP" => array(
                "NEW",
                "HIT",
                "RECOMMEND"
            ),
            "PATH_TO_ORDER" => "/personal/basket/order.php",
            "HIDE_COUPON" => "N",
            "PRICE_VAT_SHOW_VALUE" => "N",
            "USE_PREPAYMENT" => "N",
            "QUANTITY_FLOAT" => "Y",
            "CORRECT_RATIO" => "Y",
            "AUTO_CALCULATION" => "Y",
            "SET_TITLE" => "Y",
            "ACTION_VARIABLE" => "basketAction",
            "COMPATIBLE_MODE" => "Y",
            "EMPTY_BASKET_HINT_PATH" => "/",
            "OFFERS_PROPS" => array(
            ),
            "BASKET_IMAGES_SCALING" => "adaptive",
            "USE_GIFTS" => "N",
            "USE_ENHANCED_ECOMMERCE" => "N",
            "COMPONENT_TEMPLATE" => "template.1",
            "SETTINGS_USE" => "Y",
            "QUICK_VIEW_USE" => "Y",
            "TOTAL_BLOCK_FIXED_MODE" => "N",
            "ADDITIONAL_PICT_PROP_13" => "-",
            "ADDITIONAL_PICT_PROP_14" => "-",
            "QUICK_VIEW_SLIDE_USE" => "N",
            "QUICK_VIEW_TEMPLATE" => "2",
            "QUICK_VIEW_PROPERTY_CODE" => array(
                "PROPERTY_TYPE",
                "PROPERTY_QUANTITY_OF_STRIPS",
                "PROPERTY_POWER",
                "PROPERTY_PROCREATOR",
                "PROPERTY_SCOPE",
                "PROPERTY_DISPLAY",
                "PROPERTY_WEIGTH",
                "PROPERTY_ENERGY_CONSUMPTION",
                "PROPERTY_SETTINGS",
                "PROPERTY_COMPOSITION",
                "PROPERTY_LENGTH",
                "PROPERTY_SEASON",
                "PROPERTY_PATTERN"
            ),
            "HIDE_NOT_AVAILABLE_OFFERS" => "N",
            "QUICK_VIEW_IBLOCK_TYPE" => "catalogs",
            "QUICK_VIEW_IBLOCK_ID" => "16",
            "OFFERS_PROPERTY_CODE" => array(
            ),
            "OFFERS_FIELD_CODE" => array(
            ),
            "OFFERS_SORT_FIELD" => "sort",
            "OFFERS_SORT_ORDER" => "asc",
            "OFFERS_SORT_FIELD2" => "id",
            "OFFERS_SORT_ORDER2" => "desc",
            "SECTION_URL" => "",
            "DETAIL_URL" => "",
            "CACHE_TYPE" => "A",
            "CACHE_TIME" => "36000000",
            "CACHE_GROUPS" => "Y",
            "BASKET_URL" => "/personal/basket.php",
            "PRICE_CODE" => array(
                "BASE"
            ),
            "USE_PRICE_COUNT" => "Y",
            "SHOW_PRICE_COUNT" => "1",
            "PRICE_VAT_INCLUDE" => "N",
            "ADD_PROPERTIES_TO_BASKET" => "N",
            "PARTIAL_PRODUCT_PROPERTIES" => "N",
            "LINK_IBLOCK_TYPE" => "",
            "LINK_IBLOCK_ID" => "",
            "LINK_PROPERTY_SID" => "",
            "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
            "USE_MAIN_ELEMENT_SECTION" => "N",
            "DISABLE_INIT_JS_IN_COMPONENT" => "N",
            "CONVERT_CURRENCY" => "Y",
            "USE_COMPARE" => "Y",
            "QUICK_VIEW_PROPERTY_MARKS_HIT" => "HIT",
            "QUICK_VIEW_PROPERTY_MARKS_NEW" => "NEW",
            "QUICK_VIEW_PROPERTY_MARKS_RECOMMEND" => "RECOMMEND",
            "QUICK_VIEW_PROPERTY_PICTURES" => "PICTURES",
            "QUICK_VIEW_PROPERTY_ORDER_USE" => "",
            "QUICK_VIEW_OFFERS_PROPERTY_PICTURES" => "PICTURES",
            "QUICK_VIEW_OFFERS_PROPERTY_PICTURE_DIRECTORY" => "",
            "QUICK_VIEW_OFFERS_VARIABLE_SELECT" => "offer",
            "QUICK_VIEW_PROPERTY_TEXT" => "",
            "QUICK_VIEW_LAZYLOAD_USE" => "Y",
            "QUICK_VIEW_MARKS_SHOW" => "Y",
            "QUICK_VIEW_WEIGHT_SHOW" => "Y",
            "QUICK_VIEW_QUANTITY_SHOW" => "Y",
            "QUICK_VIEW_QUANTITY_MODE" => "number",
            "QUICK_VIEW_ADDITIONAL_PRODUCTS" => "Y",
            "QUICK_VIEW_ACTION" => "detail",
            "QUICK_VIEW_DESCRIPTION_SHOW" => "Y",
            "QUICK_VIEW_DESCRIPTION_MODE" => "preview",
            "QUICK_VIEW_GALLERY_PANEL" => "Y",
            "QUICK_VIEW_GALLERY_PREVIEW" => "Y",
            "QUICK_VIEW_INFORMATION_PAYMENT" => "Y",
            "QUICK_VIEW_PAYMENT_URL" => "",
            "QUICK_VIEW_INFORMATION_SHIPMENT" => "Y",
            "QUICK_VIEW_SHIPMENT_URL" => "",
            "QUICK_VIEW_TIMER_SHOW" => "Y",
            "QUICK_VIEW_TIMER_TIME_ZERO_HIDE" => "Y",
            "QUICK_VIEW_TIMER_MODE" => "discount",
            "QUICK_VIEW_TIMER_ELEMENT_ID_INTRODUCE" => "N",
            "QUICK_VIEW_TIMER_TIMER_SECONDS_SHOW" => "N",
            "QUICK_VIEW_TIMER_TIMER_QUANTITY_SHOW" => "Y",
            "QUICK_VIEW_TIMER_TIMER_QUANTITY_ENTER_VALUE" => "N",
            "QUICK_VIEW_TIMER_TIMER_PRODUCT_UNITS_USE" => "Y",
            "QUICK_VIEW_TIMER_TIMER_QUANTITY_HEADER_SHOW" => "Y",
            "QUICK_VIEW_TIMER_TIMER_QUANTITY_HEADER" => "Остаток",
            "QUICK_VIEW_TIMER_TIMER_HEADER_SHOW" => "Y",
            "QUICK_VIEW_TIMER_TIMER_HEADER" => "До конца акции",
            "QUICK_VIEW_TIMER_SETTINGS_USE" => "N",
            "QUICK_VIEW_TIMER_LAZYLOAD_USE" => "N",
            "QUICK_VIEW_TIMER_TIMER_QUANTITY_OVER" => "Y",
            "QUICK_VIEW_TIMER_TIMER_TITLE_SHOW" => "Y",
            "LABEL_PROP_MOBILE" => array(
                "NEW",
                "HIT",
                "RECOMMEND"
            ),
            "LABEL_PROP_POSITION" => "top-left",
            "QUICK_VIEW_TIMER_TIMER_TITLE_ENTER" => "N",
            "CURRENCY_ID" => "RUB",
            "COMPARE_PATH" => "/catalog/compare.php",
            "COMPARE_NAME" => "compare",
            "QUICK_VIEW_DELAY_USE" => "N",
            "QUICK_VIEW_MARKS_ORIENTATION" => "horizontal",
            "QUICK_VIEW_PROPERTIES_SHOW" => "N",
            "QUICK_VIEW_DETAIL_SHOW" => "N"
        ),
        false
    ); ?>
<?php } else { ?>
    <? $APPLICATION->IncludeComponent(
        "intec:startshop.basket",
        ".default",
        array(
            "COMPONENT_TEMPLATE" => ".default",
            "CURRENCY" => "rub",
            "REQUEST_VARIABLE_ACTION" => "action",
            "REQUEST_VARIABLE_ITEM" => "item",
            "REQUEST_VARIABLE_QUANTITY" => "quantity",
            "REQUEST_VARIABLE_PAGE" => "page",
            "URL_BASKET_EMPTY" => "",
            "USE_ITEMS_PICTURES" => "Y",
            "USE_BUTTON_CLEAR" => "Y",
            "USE_BUTTON_BASKET" => "Y",
            "USE_SUM_FIELD" => "Y",
            "TITLE_BASKET" => "",
            "TITLE_ORDER" => "Оформление заказа",
            "TITLE_PAYMENT" => "Оплата",
            "URL_ORDER_CREATED" => "/personal/profile/orders/#ID#/",
            "USE_ADAPTABILITY" => "Y",
            "REQUEST_VARIABLE_PAYMENT" => "payment",
            "REQUEST_VARIABLE_VALUE_RESULT" => "result",
            "REQUEST_VARIABLE_VALUE_SUCCESS" => "success",
            "REQUEST_VARIABLE_VALUE_FAIL" => "fail",
            "URL_ORDER_CREATED_TO_USER" => "/personal/profile/",
            "AJAX_MODE" => "N",
            "USE_BUTTON_FAST_ORDER" => "N",
            "USE_BUTTON_CONTINUE_SHOPPING" => "Y",
            "URL_CATALOG" => "/catalog/",
            "VERIFY_CONSENT_TO_PROCESSING_PERSONAL_DATA" => "Y",
            "URL_RULES_OF_PERSONAL_DATA_PROCESSING" => "/company/consent/",
            "USE_FAST_ORDER" => "N"
        ),
        false
    ); ?>
<?php } ?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>